server:
  port: 8081
spring:
  application:
    name: employees-gateway
  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true
      routes:
        - id: employees
          uri: http://localhost:8080
          predicates:
            - Path=/api/employees/**
          filters:
            - LocalResponseCache=30m,500MB
